src/AppBundle/Entity/Car.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Car
 *
 * @ORM\Table(name="car")
 * @ORM\Entity
 */
class Car
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @Gedmo\Slug(fields={"name"})
     * @ORM\Column(name="slug", type="string", length=255)
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var string
     *
     * @ORM\Column(name="picture", type="string", length=255)
     */
    private $picture;

    /**
     * @var string
     *
     * @ORM\Column(name="model", type="text", nullable=true)
     */
    private $model;

    /**
     * @var string
     *
     * @ORM\Column(name="price", type="decimal")
     */
    private $price;

    /**
     * @var integer
     * 
     * @ORM\Column(name="nb_orders", type="integer")
     */
    private $nbOrders = 0;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="nb_reviews", type="integer")
     */
    private $nbReviews = 0;
    
    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="createdAt", type="datetime")
     */
    private $createdAt;
    
    /**
     * @var ArrayCollection
     *
     * * @ORM\OneToMany(targetEntity="CarReview", mappedBy="car")
     */
    protected $reviews;

    /**
     * @var ArrayCollection
     * 
     * @ORM\ManyToMany(targetEntity="CarCategory", inversedBy="cars")
     */
    protected $categories;
    
    /**
     * @var ArrayCollection
     *
     * @ORM\ManyToMany(targetEntity="CarOrder", mappedBy="cars")
     */
    protected $orders;

    public function __construct()
    {
        $this->reviews = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    public function __toString()
    {
        return $this->getName();
    }
    
    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Car
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Car
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Car
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set picture
     *
     * @param string $picture
     * @return Car
     */
    public function setPicture($picture)
    {
        $this->picture = $picture;

        return $this;
    }

    /**
     * Get picture
     *
     * @return string 
     */
    public function getPicture()
    {
        return $this->picture;
    }

    /**
     * Set model
     *
     * @param string $model
     * @return Car
     */
    public function setModel($model)
    {
        $this->model = $model;

        return $this;
    }

    /**
     * Get model
     *
     * @return string 
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * Set price
     *
     * @param string $price
     * @return Car
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return string 
     */
    public function getPrice()
    {
        return $this->price;
    }

    /**
     * Set createdAt
     *
     * @param \DateTime $createdAt
     * @return Car
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime 
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Add reviews
     *
     * @param \AppBundle\Entity\CarReview $reviews
     * @return Car
     */
    public function addReview(\AppBundle\Entity\CarReview $reviews)
    {
        $this->reviews[] = $reviews;

        return $this;
    }

    /**
     * Remove reviews
     *
     * @param \AppBundle\Entity\CarReview $reviews
     */
    public function removeReview(\AppBundle\Entity\CarReview $reviews)
    {
        $this->reviews->removeElement($reviews);
    }

    /**
     * Get reviews
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getReviews()
    {
        return $this->reviews;
    }

    
    public function getApprovedReviews()
    {
        $reviews = array();
        foreach ($this->getReviews() as $review) {
            if ($review->getIsModerated()) {
                $reviews[] = $review;
            }
        }
        
        return $reviews;
    }
    
    /**
     * Add categories
     *
     * @param \AppBundle\Entity\CarCategory $categories
     * @return Car
     */
    public function addCategory(\AppBundle\Entity\CarCategory $categories)
    {
        $this->categories[] = $categories;

        return $this;
    }

    /**
     * Remove categories
     *
     * @param \AppBundle\Entity\CarCategory $categories
     */
    public function removeCategory(\AppBundle\Entity\CarCategory $categories)
    {
        $this->categories->removeElement($categories);
    }

    /**
     * Get categories
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Add orders
     *
     * @param \AppBundle\Entity\CarOrder $orders
     * @return Car
     */
    public function addOrder(\AppBundle\Entity\CarOrder $orders)
    {
        $this->orders[] = $orders;

        return $this;
    }

    /**
     * Remove orders
     *
     * @param \AppBundle\Entity\CarOrder $orders
     */
    public function removeOrder(\AppBundle\Entity\CarOrder $orders)
    {
        $this->orders->removeElement($orders);
    }

    /**
     * Get orders
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getOrders()
    {
        return $this->orders;
    }

    /**
     * Set nbOrders
     *
     * @param integer $nbOrders
     * @return Car
     */
    public function setNbOrders($nbOrders)
    {
        $this->nbOrders = $nbOrders;

        return $this;
    }

    /**
     * Get nbOrders
     *
     * @return integer 
     */
    public function getNbOrders()
    {
        return $this->nbOrders;
    }

    /**
     * Set nbReviews
     *
     * @param integer $nbReviews
     * @return Car
     */
    public function setNbReviews($nbReviews)
    {
        $this->nbReviews = $nbReviews;

        return $this;
    }

    /**
     * Get nbReviews
     *
     * @return integer 
     */
    public function getNbReviews()
    {
        return $this->nbReviews;
    }
}

src/AppBundle/Form/CarType.php
<?php

namespace AppBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class CarType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('slug')
            ->add('description')
            ->add('picture')
            ->add('model')
            ->add('price')
            ->add('nbOrders')
            ->add('nbReviews')
            ->add('createdAt')
            ->add('categories')
            ->add('orders')
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'AppBundle\Entity\Car'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'appbundle_car';
    }
}

src/AppBundle/Controller/CarController.php
<?php

namespace AppBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use JMS\SecurityExtraBundle\Annotation\Secure;
use AppBundle\Form\CarReviewType;
use AppBundle\Entity\CarReview;
use AppBundle\Entity\CarOrder;

/**
 * @Route("/car")
 */
class CarController extends Controller
{
    /**
     * @Secure(roles="ROLE_USER")
     *
     * @Route("/order", name="car_order")
     * @Template()
     */
    public function orderAction()
    {
        $cart = $this->get('cart');
    
        $cars = $cart->getCars();
        if (count($cars) < 1) {
            // samochód jest już w koszyku
            $this->addFlash('error', "Nie możesz złożyć zamówienia - koszyk jest pusty.");
        }
    
        $user = $this->getUser();
    
        $order = new CarOrder();
        $order->setUser($user);
        foreach ($cars as $car) {
            $order->addCar($car);
            
            // aktualizuj liczbę zamówień dla samochodu
            $car->setNbOrders($car->getNbOrders() + 1);
        }
    
        $em = $this->getDoctrine()->getManager();
    
        $em->persist($order);
        $em->flush();
    
        // wyczyść koszyk
        $cart->clear();
    
        // wyślij miala ze szczegółami płatności
        $mailer = $this->get('mailer');
        
        $message = $mailer->createMessage()
            ->setSubject('CarShop.pl - potwierdzenie zamówienia')
            ->setFrom('no-reply@carshop.pl')
            ->setTo($user->getEmail())
            ->setBody($this->renderView(
                'AppBundle:Car:emailConfirmation.html.twig',
                array('user' => $user)
        ),'text/html');
        
        $mailer->send($message);
        
        $this->addFlash('notice', "Zamówienie zostało zapisane. Na podany adres e-mail zostały wysłane informacje na temat płatności.");
    
        return $this->redirectToRoute('order_confirm', array('id' => $order->getId()));
    }
    
    /**
     * @Route("/{slug}", name="car_show")
     * @Template()
     */
    public function showAction($slug)
    {
        $car = $this->getDoctrine()->getRepository('AppBundle:Car')
            ->findOneBy(array('slug' => $slug));
        
        if (!$car) {
            throw $this->createNotFoundException("Samochód nie został odnaleziony.");
        }
        
        return array(
            'car' => $car
        );
    }

    /**
     * @Secure(roles="ROLE_USER")
     * 
     * @Route("/{slug}/rent", name="car_rent")
     * @Template()
     */
    public function rentAction($slug)
    {
        $car = $this->getDoctrine()->getRepository('AppBundle:Car')
            ->findOneBy(array('slug' => $slug));
        
        if (!$car) {
            throw $this->createNotFoundException("Samochód nie został odnaleziony.");
        }
        
        $cart = $this->get('cart');
        
        if ($cart->has($car)) {
            // Samochód jest już w koszyku
            $this->addFlash('error', "Ten samochód znajduje się już w Twoim koszyku.");
        } else {
            $cart->add($car);
            $this->addFlash('notice', "Samochód został pomyślnie dodany do koszyka.");
        }
        
        return $this->redirect($this->getRequest()->headers->get('referer'));
    }
    
    /**
     * @Route("/{slug}/watch", name="car_watch")
     * @Template()
     */
    public function watchAction($slug)
    {
        $car = $this->getDoctrine()->getRepository('AppBundle:Car')
            ->findOneBy(array('slug' => $slug));

        if (!$car) {
            throw $this->createNotFoundException("Samochód nie został odnaleziony.");
        }
        
        if (!$this->getUser()->isOrderedCar($car)) {
            $this->addFlash('error', 'Ten samochód nie został jeszcze opłacony!');
            return $this->redirectToRoute('homepage');
        }
        
        $this->addFlash('notice', "Odtwarzanie");
    
        return $this->redirect($this->getRequest()->headers->get('referer'));
    }
    
    /**
     * @Secure(roles="ROLE_USER")
     * 
     * @Route("/{slug}/add-review", name="car_add_review")
     * @Template()
     */
    public function addReviewAction($slug)
    {
        $car = $this->getDoctrine()->getRepository('AppBundle:Car')
            ->findOneBy(array('slug' => $slug));
        
        if (!$car) {
            throw $this->createNotFoundException("Samochód nie został odnaleziony.");
        }
        
        $review = new CarReview();
        $review->setCar($car);
        $review->setUser($this->getUser());
        
        $form = $this->createForm(new CarReviewType(), $review);
        
        $form->handleRequest($this->getRequest());
        
        if ($form->isValid()) {
            
            $em = $this->getDoctrine()->getManager();
            $em->persist($review);
            
            // zwiększa liczbę opinii
            $car->setNbReviews($car->getNbReviews() + 1);
            
            $em->flush();
            
            $this->addFlash('notice', "Recenzja została pomyślnie dodana i oczekuje na moderację.");
            return $this->redirectToRoute('car_show', array('slug' => $car->getSlug()));
        }
        
        return array(
            'car' => $car,
            'form'  => $form->createView()
        );
    }
    
}

src/AppBundle/Resources/views/Car/addReview.html.twig
{% extends "::base.html.twig" %}

{% block title %}{{ car.name }} - dodaj recenzję{% endblock %}

{% block body %}


  <div class="page-header">
    <h1>{{ block('title') }}</h1>
  </div>
  
  <div>
    
    {{ form_start(form) }}
    {{ form_widget(form) }}
    {{ form_end(form) }}
    
  </div>

{% endblock %}

src/AppBundle/Resources/views/Car/emailConfirmation.html.twig
Witaj, {{ user }}

Wiadomość email z informacjami of formie, warunkach i terminie
płatności

Zespół,

CarShop.pl

src/AppBundle/Resources/views/Car/list.html.twig
{% block logo %} 
 <div class="jumbotron">
    
  <table>
  
    <tr>
    
  <td width="55%">
      <center><h1>Potrzebujesz samochodu?</h1></center>
  </td>
  
  <td>
        <center><p><a class="btn btn-xlarge btn-success" href="{{path('fos_user_security_login')}}" role="button">Zaloguj się</a></p></center>
  </td>
    </tr>
  </table>
  
      </div>

 {% endblock %}
    <div class="row">
    <div class="row marketing">
        <div class="col-lg-6">
          <h1>Nasze samochody:</h1>
          <p>Poniższe samochody dostępne są do Twojej dyspozycji!</p>
    </div>
  </div>
            {% for car in cars %}
    <div class = "col-sm-6 col-md-3">
      <a href="{{ path('car_show', {'slug': car.slug}) }}" title="Zobacz więcej o: {{ car.name }}" class = "thumbnail">
         <img src = "{{ asset('uploads/' ~ car.picture) }}" alt = "Generic placeholder thumbnail">
      
      <p>{{ car.name }}</p>
          
        </a> 
          
   </div>
    {% endfor %}  
   </div>

src/AppBundle/Resources/views/Car/list2.html.twig
   <div class="row">

            {% for car in cars %}
    <div class = "col-sm-6 col-md-3">
      <a href="{{ path('car_show', {'slug': car.slug}) }}" title="Zobacz więcej o: {{ car.name }}" class = "thumbnail">
         <img src = "{{ asset('uploads/' ~ car.picture) }}" alt = "Generic placeholder thumbnail">
      
      <p>{{ car.name }}</p>
          
        </a> 
          
   </div>
    {% endfor %}  
   </div>

src/AppBundle/Resources/views/Car/rent.html.twig
{% extends "::base.html.twig" %}

{% block title %}AppBundle:Car:rent{% endblock %}

{% block body %}
<h1>Welcome to the Car:rent page</h1>
{% endblock %}

src/AppBundle/Resources/views/Car/show.html.twig
{% extends "::base.html.twig" %}

{% block title %}{{ car.name }}{% endblock %}

{% block body %}

<h1>{{ block('title') }}</h1>
  
<div class="row">
    
    <img class="pull-right" width=400 src="{{ asset('uploads/' ~ car.picture) }}" />
    
    {% for category in car.categories %}
        <a class="btn btn-lg btn-success" href="{{ path('category_show', {'slug': category.slug}) }}">{{ category.name }}</a>
    {% endfor %}
  <br>  <br>
    <h3>Cena <span class="label label-default">{{ car.price }} zł</span></h3>
   <br>  
    <h3>Opis</h3>
    <p>{{ car.description }}</p>
  
  <br>
    <h3>Model</h3>
    <p>{{ car.model|raw }}</p>
   <br>  
    <a href="{{ path('car_rent', {'slug': car.slug}) }}" class="btn btn-info">Wypożycz</a>
  

  <br><br>
  <center>  <h1>Recenzje {% if app.user %}<a href="{{ path('car_add_review', {'slug': car.slug}) }}" class=" pull-right btn btn-success">Dodaj recenzje</a>{% endif %}</h1></center></h1>
    {% if not app.user %}
        <p><a href="{{ path('fos_user_security_login') }}">Zaloguj się</a> by móc dodawać recenzje.</p>
    {% endif %}
    
    <ul class="list-group">
    {% for revision in car.approvedReviews %}
        
        <li class="list-group-item ">
            <span class="pull-right">Dodana dnia: {{ revision.createdAt|date('Y-m-d H:i:s') }}</span>
            <h4 class="list-group-item-heading">{{ revision.user }}</h4>
            <p class="list-group-item-text">{{ revision.content }}</p>
        </li>
        
    {% else %}
    
        <li class="list-group-item ">Ten Samochód nie posiada jeszcze żadnych recenzji</li>
      
    {% endfor %}
    </ul>
    
</div>
  
{% endblock %}